In [1]:
import pandas as pd
import numpy as np

In [2]:
def script(df, x_word):
    return df[df.Запрос.str.find(x_word) != -1]

def script_minus(df, xm_word):
    df1 = df[df.Запрос.str.find(xm_word) != -1]
    return pd.concat([df, df1]).drop_duplicates(keep=False)

def script_cpc(df, x_value):
    df['СPC Yandex'] = [x.replace(',', '.') if type(x) is not float else x for x in df['СPC Yandex'] ]
    df['СPC Yandex'] = df['СPC Yandex'].astype(float)
    return df[df['СPC Yandex'] <= x_value]

def main(path, x_word = '', xm_word = '', x_value = np.nan):
    df = pd.read_csv(path, header = 0, delimiter= ';')
    if x_word != '':
        df = script(df, x_word)
    if xm_word != '':
        df = script_minus(df, xm_word)
    if x_value is not np.nan:
        df = script_cpc(df, x_value)
        
    df.to_csv("output.csv")
    return df

,Запрос,Показы Yandex,СPC Yandex,Рекламодатели Yandex,Тип фразы,Исходный запрос
15,растаможивание,92,"40,12",4.0,связанные,импорт из китая в россию
16,россия-китай,90,"0,44",NaN,связанные,импорт из китая в россию
17,китай россия,89,"0,44",NaN,связанные,импорт из китая в россию
21,граница россии и китая,70,"0,04",NaN,связанные,импорт из китая в россию
22,растамаживать,67,"8,36",6.0,связанные,импорт из китая в россию
...,...,...,...,...,...,...
35152,соглашение между участниками,1,NaN,3.0,связанные,договор с партнером
35155,субъект соглашения,1,NaN,NaN,связанные,договор с партнером
35163,согла,1,NaN,2.0,связанные,договор с партнером
35165,соглашение между администрациями,1,NaN,3.0,связанные,договор с партнером
35172,партнерство отношениях,1,NaN,NaN,связанные,договор с партнером

In [56]:
import chardet
with open('clustering/zaprosy_all.CSV', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large

df = pd.read_csv('clustering/zaprosy_all.CSV', encoding = result['encoding'], delimiter = '\t')

phrases = df['Запрос']
phrases = phrases.to_list()

In [66]:
stop = pd.read_csv('stop_words.csv', header = 0)
minus = pd.read_csv('minus_words.csv', header = 0)

In [62]:
minus_ind = []
df.Запрос[df.Запрос.str.find('импорт') != -1].index.to_list() # индексы с этим словом
for word in minus.minus:
    df = script_minus(df, word)  
df

               minus
0             амазон
1             amazon
2         aliexpress
3             taobao
4           aeroflot
..               ...
774        сервисные
775  поремонтировать
776           замена
777           замены
778         поменять

[779 rows x 1 columns]

In [69]:
df.to_csv('clean_zaprosy.csv')

In [12]:
path = 'requests.csv'
x_word = 'платья'


main(path, x_word = x_word, xm_word = 'фото', x_value = 7)

,Запрос,Запрос.1,Показы Yandex,СPC Yandex,Рекламодатели Yandex,Тип фразы,Исходный запрос
335,личи платья,личи платья,23,0.98,NaN,связанные,12 storeez
371,101 дресс платья,101 дресс платья,20,6.30,4.0,связанные,12 storeez
517,платья инстаграм,платья инстаграм,12,0.76,NaN,связанные,12 storeez
685,платья старые,платья старые,8,0.04,1.0,связанные,12 storeez
762,магазин женского платья в москве,магазин женского платья в москве,6,0.86,8.0,связанные,12 storeez
...,...,...,...,...,...,...,...
64174,модные тенденции платья,модные тенденции платья,2,0.40,1.0,связанные,модная одежда для девушек
64357,какие платья модные в этом году,какие платья модные в этом году,1,0.04,4.0,"связанные,вопросы",модная одежда для девушек
65217,контур платья,контур платья,1,0.04,NaN,связанные,модная одежда для девушек
65868,модные тенденции в платьях,модные тенденции в платьях,1,0.04,NaN,связанные,модная одежда для девушек
72760,пальто платья,пальто платья,1,0.88,NaN,связанные,заказать пальто женское по интернету